### ISSUE TITLE
Does not build on non-sparc systems with -Werror

### ISSUE THREAD

**Issue by glaubitz** [esnowberg/grub2-sparc#2]
Hi!

grub defaults to building with -Werror (see the --disable-werror flag), so we have to make sure that the compiler does not produce any warnings during build.

Unfortunately, there are a couple of warnings when building sparc-next-v1 on non-sparc targets because some functions are either unused or implicitly defined.

It seems to affect grub-core/disk/ieee1275/ofdisk.c only. My first approach was to use #ifdef __sparc__ #endif, but with that we have to add quite a large number of these guards.

I'm looking into other solutions now. Either we don't build ofdisk support on non-sparc targets at all or we use the sparc64-specifc ieee1275.h header on the other platforms as well.

**Comment by glaubitz** [comment]
I just tried on _powerpc_ which is also _ieee1275_. I removed my patch from #1.

It does not build on _powerpc_ and fails with:

```
In file included from grub-core/osdep/ofpath.c:2:0:
grub-core/osdep/linux/ofpath.c:418:1: error: 'check_hba_identifiers' defined but not used [-Werror=unused-function]
 check_hba_identifiers(const char *sysfs_path, int *vendor, int *device_id)
 ^~~~~~~~~~~~~~~~~~~~~
grub-core/osdep/linux/ofpath.c:53:32: error: 'sparc_lsi_hba' defined but not used [-Werror=unused-variable]
 static struct ofpath_sparc_hba sparc_lsi_hba[] = {
                                ^~~~~~~~~~~~~
```

So, we really need to make sure we cleanly separate sparc-specifc code from the generic _ieee1275_ code.

**Comment by esnowberg** [comment]
I believe I have this all fixed now.  Try out the changes in the sparc_next_v2 branch.

**Comment by glaubitz** [comment]
Just did testbuilds on _powerpc_ (32-Bit Big-Endian), _ppc64el_ (POWER8 Little-Endian) and _ppc64_ (64-Bit Big-Endian, POWER5).  _powerpc_ and _ppc64el_ build fine, _ppc64_ bails out with:

````
gcc -Os -Wall -W -Wshadow -Wpointer-arith -Wundef -Wchar-subscripts -Wcomment -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wfloat-equal -Wformat-extra-args -Wformat-security -Wformat-y2k -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wmain -Wmissing-braces -Wmissing-format-attribute -Wmultichar -Wparentheses -Wreturn-type -Wsequence-point -Wshadow -Wsign-compare -Wswitch -Wtrigraphs -Wunknown-pragmas -Wunused -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value  -Wunused-variable -Wwrite-strings -Wnested-externs -Wstrict-prototypes -g -Wredundant-decls -Wmissing-prototypes -Wmissing-declarations -Wcast-align  -Wextra -Wattributes -Wendif-labels -Winit-self -Wint-to-pointer-cast -Winvalid-pch -Wmissing-field-initializers -Wnonnull -Woverflow -Wvla -Wpointer-to-int-cast -Wstrict-aliasing -Wvariadic-macros -Wvolatile-register-var -Wpointer-sign -Wmissing-include-dirs -Wmissing-prototypes -Wmissing-declarations -Wformat=2 -mbig-endian -m32 -freg-struct-return -msoft-float -fno-dwarf2-cfi-asm -fno-asynchronous-unwind-tables -fno-unwind-tables -Qn -fno-PIE -fno-pie -fno-stack-protector -Wtrampolines -Werror  -mcpu=powerpc -ffreestanding   -mbig-endian -m32 -Wl,--build-id=none  -nostdlib -Wl,-N -Wl,-r,-d   -o disk.module lib/disk_module-disk.o   
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
Makefile:24255: recipe for target 'disk.module' failed
make[3]: *** [disk.module] Error 1
make[3]: Leaving directory '/home/glaubitz/grub2-sparc/grub-core'
Makefile:23526: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/glaubitz/grub2-sparc/grub-core'
Makefile:10892: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/glaubitz/grub2-sparc'
Makefile:3118: recipe for target 'all' failed
make: *** [all] Error 2
````

However, this might also be related to default linker flags on Debian.

**Comment by mator** [comment]
I'm interested on how to build grub on sparc as well...

**Comment by glaubitz** [comment]
Huh? It builds just fine on sparc64. What's your problem?

Also, this issue was about grub2 with Eric's sparc64 patches not building on any architectures other than sparc64 which was fixed in the sparc-next-v2 branch. I am closing the issue now because it has actually been solved.

If you see other problems, please open a new issue.
